# -*- coding: utf-8 -*-
"""JASWANTH_DAY29_DIY_SOLUTION_DOC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yE8zT27azWDg5Dc2OaI3jV1aLNMY7xHK

Q1. Problem Statement: Hypothesis Testing
Write a Python program that reads the Life Expectancy Data.csv (provided on
LMS) file into a DataFrame, then drops null values and performs hypothesis
testing for the given scenario.
H0:u = average life expectancy of Afghanistan is the same as the average Life
expectancy of the world (Null hypothesis)
H1:u = average life expectancy of Afghanistan is not the same as the average Life
expectancy of the world (Alternate hypothesis)
1. Load the dataset into a data frame
2. Drop all missing values
3. Take the mean of the whole target variable and extract data from
‘Afghanistan’
4. consider a significance level of 0.05, perform a T-tail test using the stats
library and calculate P-value and conclude hypothesis testing.
"""

import pandas as pd
import numpy as np
import seaborn as sys

a=pd.read_csv('Life Expectancy Data.csv')
a.head()

b=a.isnull().sum()
b

b=a.dropna()
b

b.isnull().sum()

c=a.rename(columns={'Life expectancy ':'Life'})
c

m=c['Life'].mean()
m

d=c[c.Country ==	'Afghanistan']
d=d.sample(5,random_state=1)
d

d['Life'].mean()

"""4.consider a significance level of 0.05, perform a T-tail test using the stats library and calculate P-value and conclude hypothesis testing."""

alpha=0.05
p=1-alpha/2
from scipy.stats import t
df=4
critical_value = t.ppf(p,df)
print('The critical value of 95% level and with 4 degrees of freedom :',critical_value)

from scipy.stats import ttest_1samp
# Calculating t-statistic and p-value
t_statistic, p_value = ttest_1samp(d['Life'],m)
print('The t-statistic value is',t_statistic)
print('The p-value is',p_value)

p_value
'{:.8f}'.format(p_value)

if(p_value<alpha):
  print('we fail to reject the null hypothesis\nThe average life expectancy of afghanistan is not same as avg life expectancy of world.')
else: 
    print('we reject the null hypothesis.')